name: Life Tracker
permalink: :year/:month/:day/:title
#baseurl: /jekyll-theme-diary
baseurl: ""
url: "https://lifetracker.work"

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : 
  github : 
  twitter : 

# Links in the navigation, you can modify both link name and link url
nav:
   Home: ""
   About: "about"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed
